spring.application.name=be

# DevTools Restart 활성화
spring.devtools.restart.enabled=true

# 추가로 감시할 폴더 (Java 소스)
spring.devtools.restart.additional-paths=src/main/java

# LiveReload (브라우저 자동 새로고침)
spring.devtools.livereload.enabled=true