spring.application.name=be

# DevTools Restart 강제 폴링 모드
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=500
spring.devtools.restart.quiet-period=400
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.log-condition-evaluation-delta=false