spring.application.name=be

# DevTools Restart 활성화
spring.devtools.restart.enabled=true

# 추가로 감시할 폴더 (Java 소스)
spring.devtools.restart.additional-paths=src/main/java

# LiveReload (브라우저 자동 새로고침)
spring.devtools.livereload.enabled=true


cloud.aws.credentials.access-key=YOUR_ACCESS_KEY
cloud.aws.credentials.secret-key=YOUR_SECRET_KEY
cloud.aws.s3.bucket=your-bucket-name
cloud.aws.region.static=ap-northeast-2

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.resources.static-locations=classpath:/static/,file:uploads/

